name: ClassSMPPlugin
version: '1.0-SNAPSHOT'
main: me.stierprogrammer.classSMPPlugin.ClassSMPPlugin
api-version: '1.21'
commands:
  back:
    description: Takes back to your last death location!
    usage: /<command>
  home:
    description: Teleports you to your home
    usage: /<command> <name>
  sethome:
    description: Allows you to set your home
    usage: /<command> <name>
  homes:
    description: Shows you all of your homes
    usage: /<command>